export type PairManifest = {
  slug: string;
  replayLogPath: string;
  rawL2LogPath: string;
  strategy: string;
  slotStartMs: number;
  slotEndMs: number;
  captureStartedAtMs: number;
  captureEndedAtMs: number;
  runtimeStartedAtMs: number;
  runtimeEndedAtMs: number;
  recorderStartedAtMs: number;
  recorderEndedAtMs: number;
  runtimeExitCode: number | null;
  recorderExitCode: number | null;
  replayEventCount: number;
  rawL2EventCount: number;
  rawL2BookEventCount: number;
  rawL2TradeEventCount: number;
  replayFirstEventTsMs: number | null;
  replayLastEventTsMs: number | null;
  rawL2FirstEventTsMs: number | null;
  rawL2LastEventTsMs: number | null;
  coverageLeadMs: number | null;
  coverageTailMs: number | null;
  parseErrors: string[];
  validationErrors: string[];
  validationWarnings: string[];
  coverageVerdict: "complete" | "partial" | "missing" | "unknown";
  pairValidity: "valid" | "invalid";
  strategyLabEvidenceVerdict: "usable" | "unavailable_no_fills" | "unavailable_missing_mapping" | "unavailable_missing_l2" | "failed";
  gitCommit: string;
  commands: string[];
  validatedAtMs: number | null;
  createdAtMs: number;
};
